[project]
name = "health-oda"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "bblocks>=1.4.3, <2.0.0",
    "oda-data>=1.5.1, <2.0.0",
    "oda-reader>=1.4.1",
    "pandas>=2.2.3",
    "pyarrow>=16.1.0",
    "pydeflate>=2.3.3",
]
